// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::platform_data_type::PlatformData;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct LoadPlatformsArgs {
    pub platforms: Vec<PlatformData>,
}

impl From<LoadPlatformsArgs> for super::Reducer {
    fn from(args: LoadPlatformsArgs) -> Self {
        Self::LoadPlatforms {
            platforms: args.platforms,
        }
    }
}

impl __sdk::InModule for LoadPlatformsArgs {
    type Module = super::RemoteModule;
}

pub struct LoadPlatformsCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `load_platforms`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait load_platforms {
    /// Request that the remote module invoke the reducer `load_platforms` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_load_platforms`] callbacks.
    fn load_platforms(&self, platforms: Vec<PlatformData>) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `load_platforms`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`LoadPlatformsCallbackId`] can be passed to [`Self::remove_on_load_platforms`]
    /// to cancel the callback.
    fn on_load_platforms(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &Vec<PlatformData>) + Send + 'static,
    ) -> LoadPlatformsCallbackId;
    /// Cancel a callback previously registered by [`Self::on_load_platforms`],
    /// causing it not to run in the future.
    fn remove_on_load_platforms(&self, callback: LoadPlatformsCallbackId);
}

impl load_platforms for super::RemoteReducers {
    fn load_platforms(&self, platforms: Vec<PlatformData>) -> __sdk::Result<()> {
        self.imp
            .call_reducer("load_platforms", LoadPlatformsArgs { platforms })
    }
    fn on_load_platforms(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &Vec<PlatformData>) + Send + 'static,
    ) -> LoadPlatformsCallbackId {
        LoadPlatformsCallbackId(self.imp.on_reducer(
            "load_platforms",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::LoadPlatforms { platforms },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, platforms)
            }),
        ))
    }
    fn remove_on_load_platforms(&self, callback: LoadPlatformsCallbackId) {
        self.imp.remove_on_reducer("load_platforms", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `load_platforms`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_load_platforms {
    /// Set the call-reducer flags for the reducer `load_platforms` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn load_platforms(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_load_platforms for super::SetReducerFlags {
    fn load_platforms(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("load_platforms", flags);
    }
}
