// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::monster_type::Monster;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `monster`.
///
/// Obtain a handle from the [`MonsterTableAccess::monster`] method on [`super::RemoteTables`],
/// like `ctx.db.monster()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.monster().on_insert(...)`.
pub struct MonsterTableHandle<'ctx> {
    imp: __sdk::TableHandle<Monster>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `monster`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MonsterTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MonsterTableHandle`], which mediates access to the table `monster`.
    fn monster(&self) -> MonsterTableHandle<'_>;
}

impl MonsterTableAccess for super::RemoteTables {
    fn monster(&self) -> MonsterTableHandle<'_> {
        MonsterTableHandle {
            imp: self.imp.get_table::<Monster>("monster"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MonsterInsertCallbackId(__sdk::CallbackId);
pub struct MonsterDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MonsterTableHandle<'ctx> {
    type Row = Monster;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Monster> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MonsterInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MonsterInsertCallbackId {
        MonsterInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MonsterInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MonsterDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MonsterDeleteCallbackId {
        MonsterDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MonsterDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Monster>("monster");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}
pub struct MonsterUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MonsterTableHandle<'ctx> {
    type UpdateCallbackId = MonsterUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MonsterUpdateCallbackId {
        MonsterUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MonsterUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Monster>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Monster>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `monster`,
/// which allows point queries on the field of the same name
/// via the [`MonsterIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.monster().id().find(...)`.
pub struct MonsterIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Monster, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MonsterTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `monster`.
    pub fn id(&self) -> MonsterIdUnique<'ctx> {
        MonsterIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MonsterIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<Monster> {
        self.imp.find(col_val)
    }
}
