// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::platform_type::Platform;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `platform`.
///
/// Obtain a handle from the [`PlatformTableAccess::platform`] method on [`super::RemoteTables`],
/// like `ctx.db.platform()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.platform().on_insert(...)`.
pub struct PlatformTableHandle<'ctx> {
    imp: __sdk::TableHandle<Platform>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `platform`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlatformTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlatformTableHandle`], which mediates access to the table `platform`.
    fn platform(&self) -> PlatformTableHandle<'_>;
}

impl PlatformTableAccess for super::RemoteTables {
    fn platform(&self) -> PlatformTableHandle<'_> {
        PlatformTableHandle {
            imp: self.imp.get_table::<Platform>("platform"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlatformInsertCallbackId(__sdk::CallbackId);
pub struct PlatformDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlatformTableHandle<'ctx> {
    type Row = Platform;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Platform> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlatformInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlatformInsertCallbackId {
        PlatformInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlatformInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlatformDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlatformDeleteCallbackId {
        PlatformDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlatformDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Platform>("platform");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}
pub struct PlatformUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlatformTableHandle<'ctx> {
    type UpdateCallbackId = PlatformUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlatformUpdateCallbackId {
        PlatformUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlatformUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Platform>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Platform>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `platform`,
/// which allows point queries on the field of the same name
/// via the [`PlatformIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.platform().id().find(...)`.
pub struct PlatformIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Platform, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlatformTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `platform`.
    pub fn id(&self) -> PlatformIdUnique<'ctx> {
        PlatformIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlatformIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<Platform> {
        self.imp.find(col_val)
    }
}
